In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pylab as plt

In [2]:
import math
pi = math.pi

def PointsInCircum(r,n=200):
    return [(math.cos(2*pi/n*x)*r,math.sin(2*pi/n*x)*r) for x in range(0,n+1)]

In [3]:
sigmas=[np.array([[1,0],[0,1]]), np.array([[5,0],[0,6]]),np.array([[5,0],[0,1]]),
        np.array([[5,3],[3,5]]),np.array([[10,0],[0,3]]),np.array([[2,0],[0,0]])]

In [4]:
sigmas

[array([[1, 0],
        [0, 1]]),
 array([[5, 0],
        [0, 6]]),
 array([[5, 0],
        [0, 1]]),
 array([[5, 3],
        [3, 5]]),
 array([[10,  0],
        [ 0,  3]]),
 array([[2, 0],
        [0, 0]])]

In [5]:
X=PointsInCircum(r=1,n=200)

In [8]:
allresults=[]
for s in sigmas:K
    results=[]
    for x in X:
        results.append(np.matmul(s,x))
    results=np.stack(results)
    #print(results)
    allresults.append(results)

In [7]:
for s,r in zip(sigmas,allresults):
    plt.figure(figsize=(10,10))
    sns.scatterplot(r[:,0],r[:,1])
    plt.xlim(-12,12)
    plt.ylim(-12,12)
    
    print(s)
    plt.show()
    plt.clf()

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 were given

<Figure size 1000x1000 with 0 Axes>